version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      rust-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: helm
    directory: /deploy/helm/qdrant-es-gateway
    schedule:
      interval: monthly
