{{- if and .Values.qdrant.apiKey (not .Values.qdrant.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qdrant-es-gateway.fullname" . }}
  labels:
    {{- include "qdrant-es-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  qdrant-api-key: {{ .Values.qdrant.apiKey | quote }}
{{- end }}
